services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:8080'
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]
    container_name: cache
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      TTL_SECONDS: 3600
    container_name: api
    depends_on:
      cache:
        condition: service_healthy
