spring:
  config:
    import: optional:secrets.yaml
  output:
    ansi:
      enabled: ALWAYS

weather:
  api:
    url: https://weather.visualcrossing.com
    path: /VisualCrossingWebServices/rest/services/timeline/{city}
    query-string: ?unitGroup=metric&key=${apiKey}&contentType=json
